### ISSUE TITLE
MySQL dialect reading column name from undefined

### ISSUE THREAD

**Issue by rijkvanzanten** [knex/knex-schema-inspector#27]
```
15:15:55 🚨 Cannot read property 'Column_name' of undefined 
TypeError: Cannot read property 'Column_name' of undefined
    at MySQL.<anonymous> (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:275:60)
    at step (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:33:23)
    at Object.next (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:14:53)
    at fulfilled (/var/www/directus_v9/node_modules/knex-schema-inspector/dist/dialects/mysql.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by MiniDigger** [comment]
Smells like #23 to me, which was fixed with #19, a simple null check, I would assume this affects all dialects (haven't looked at the code)

**Comment by rijkvanzanten** [comment]
Yeah definitely, this one over here in the `primary()` method:

https://github.com/knex/knex-schema-inspector/blob/e14f525d5302ff1d83f1467a3a1f2873f9d906ef/lib/dialects/mysql.ts#L278-L280

**Comment by rijkvanzanten** [comment]
I wrongly assumed that every table would have a primary key returned here

**Comment by tuxnese** [comment]
Hi, is there a plan to fix this issue?
