### ISSUE TITLE
Multi-line JSON not properly unescaped

### ISSUE THREAD

**Issue by glenselle** [knex/knex-schema-inspector#60]
Hey, we noticed what we believe is a breaking change introduced in `1.3.0+` versions of `knex-schema-inspector` originating from https://github.com/knex/knex-schema-inspector/commit/b5cdeae8df2647e91cfe570f6be04da8e0e17e0e which refactored `parseDefaultValue`. Previously, it correctly handled multi-line JSON but after the refactor, newlines are not properly matched and multi-line json causes Directus to crash with the following error:

```
17:05:04 🚨 Unexpected token ' in JSON at position 0 
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseDefaultValue (/Users/glen/Git/divvit/api/node_modules/knex-schema-inspector/dist/dialects/postgres.js:77:21)
    at _loop_1 (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:115:50)
    at Postgres.<anonymous> (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:119:29)
    at step (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:78:23)
    at Object.next (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:59:53)
    at fulfilled (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:50:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

The cause for this is related to a refactor of `parseDefaultValue` which changed checks from using `startsWith` and `endsWith` to a regex which doesn't properly handle multi-lines.

BEFORE (worked properly):
```javascript
if (value.startsWith("'") && value.endsWith("'")) {
  value = value.slice(1, -1);
}
```

AFTER https://github.com/knex/knex-schema-inspector/commit/b5cdeae8df2647e91cfe570f6be04da8e0e17e0e:
```javascript
value = value.replace(/^\'(.*)\'$/, '$1');
```

To fix, the regex can be modified to use `\s\S` instead of `.`
```javascript
value = value.replace(/^\'([\s\S]*)\'$/, '$1');
```

We first noticed this issue about a month ago but used older pre-built Docker images where the `knex-schema-inspector` dependency was still `1.2.2`. Directus depends on `knex-schema-inspector` but it is not hard pinned so minors are pulled in. We are fairly certain versions `1.3.0+` have this breaking change.

We found the cause of this issue by printing values from `parseDefaultValue` and the last to print before erroring out was a json value that still had single quotes `'` around it (see below). Running this through `JSON.parse` will of course fail. When we dug into the code and found the regex we noticed this formatted json string (with newlines) never matched properly. More digging and we stumbled on the old code which used `startsWith` and `endsWith` and it all started to make sense.
```
'[
    {
        "amount": "60",
        "label": "Min",
        "value": 6000
    },
    {
        "amount": "75",
        "label": "Average",
        "value": 7500,
        "default": true
    }
]'
17:05:04 🚨 Unexpected token ' in JSON at position 0 
SyntaxError: Unexpected token ' in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.parseDefaultValue (/Users/glen/Git/divvit/api/node_modules/knex-schema-inspector/dist/dialects/postgres.js:77:21)
    at _loop_1 (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:115:50)
    at Postgres.<anonymous> (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:119:29)
    at step (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:78:23)
    at Object.next (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:59:53)
    at fulfilled (/Users/glen/Git/divvit/api/node_modules/@directus/schema/dist/dialects/postgres.js:50:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by rijkvanzanten** [comment]
> Directus depends on knex-schema-inspector but it is not hard pinned so minors are pulled in. 

FWIW, Directus now has every dependency pinned to the exact versions, so this problem doesn't occur anymore in later versions 👍🏻

**Comment by glenselle** [comment]
@rijkvanzanten Would you like me to submit a PR? I'm happy to do that

**Comment by rijkvanzanten** [comment]
Yes please!

**Comment by glenselle** [comment]
Would you like me to use the regex or switch back to the `endsWith` and `startsWith`?

**Comment by rijkvanzanten** [comment]
Lets use the updated regex 👍🏻 

(cc @aidenfoxx)

**Comment by aidenfoxx** [comment]
@rijkvanzanten I think you meant to ping @Oreilles who introduced the code. I'm not familiar enough with what it's trying to accomplish to say if the regex covers all bases.

**Comment by rijkvanzanten** [comment]
Ah yeah, my bad! (doing too many things at once 😓)

**Comment by glenselle** [comment]
Hey guys, I just tried checking out the `v1.3.0` tag and it has the old (working) code. I then tried `v1.4.0` and it was also the old code. Is it possible there's a mismatch between GH tags and NPM versions? The `v1.5.0` tag had the new buggy regex.

**Comment by aidenfoxx** [comment]
Looking at the code, if it's just supposed to trim single quotes at the start and end, then the updated regex looks fine to me. 👍

**Comment by glenselle** [comment]
`\s\S` is nearly identical to `.` except that it also includes newline chars

**Comment by rijkvanzanten** [comment]
> Is it possible there's a mismatch between GH tags and NPM versions?

We push out releases/tags using `npm version <major | minor | patch>` so that should be in sync. Always a chance something went sideways tho

**Comment by glenselle** [comment]
Just opened a PR. Let me know if you would like test coverage or any changes. Thanks!

**Comment by rijkvanzanten** [comment]
Perfect, thank you! Like you said in the PR, I don't think there's tests yet for the default value JSON parsing. It would be really useful to add those if you have the time 🙂
